step1
poistargram/java-racingcar pull request #1
Opened 2022-12-29 03:23 UTC by poistargram

2022-12-30 08:49 UTC, jinuk17 requested changes
첫 미션인데 전반적으로 잘 해주셨어요 ~ 
누가한테 배웠는지 JUnit5 는 상당히 익숙하게 사용하시네요 😄 

처음이고 교육 목적이라 피드백을 좀 남겨두었습니다.
확인 후에 다시 요청 주시면 확인하도록 하겠습니다.

화이팅 👊

2022-12-30 08:49 UTC, jinuk17 commented on src/test/java/step1/StringParserTest.java
> +	private void contains(String[] array, String object){
이 구문 자체는 `assertThat(array).contains(object);` 로 직접 사용하는게 더 명확해 보이는데 private 메소드로 추출한 이유가 있을까요 ? 

private 메소드로 추출했을 경우에도 `contains` 보다는 검증하는 구문이기 때문에 assert~ 같이 검증에 대한 이름을 포함하는게 어떨까요 ?

2022-12-30 08:49 UTC, jinuk17 commented on src/test/java/step1/StringParserTest.java
> +		int index = -1;
직접 대입하지 않고 local 변수로 선언한 이유가 값의 의미를 표현하기 위해서라면 
index 보다는 invalidIndex 같이 더 명확한 네이밍으로 표현하면 어떨까요 ?

2022-12-30 08:49 UTC, jinuk17 commented on src/test/java/step1/StringParserTest.java
> +		char expectedChar = 'a';
명시적인 이름 👍

2022-12-30 08:49 UTC, jinuk17 commented on src/test/java/step1/SetTest.java
> +	@CsvSource(value = {"1:true", "2:true", "3:true", "4:false", "5:false"}, delimiter = ':')
`ParameterizedTest` 는 이제 아주 능숙하네요 👍

2022-12-30 08:49 UTC, jinuk17 commented on src/test/java/step1/SetTest.java
> +		assertThat(numbers.contains(value)).isTrue();
혹시 `assertThat(array).contains()` 로 검증하지 않고 
`assertThat(numbers.contains(value)).isTrue();` 이렇게 검증한 이유가 있을까요 ?

2022-12-30 08:49 UTC, jinuk17 commented on src/test/java/step1/AddCalculatorTest.java
> +	@DisplayName("문자열이 null인 경우 0 반환 테스트")
`@NullAndEmptySource` 이런 것도 있답니다

2022-12-30 08:49 UTC, jinuk17 commented on src/main/java/step1/AddCalculator.java
> +		String[] numbers = parseNumbers(string);
`parseNumbers(string);` 의 return 값이 String[] 인게 조금 낯서네요 ~ 
숫자가 넘어 올 것으로 예상이 됩니다.

현재 로직으로만 봐서는 split 이 더 적합해 보여요 ~

2022-12-30 08:49 UTC, jinuk17 commented on src/main/java/step1/AddCalculator.java
> +			int number = getNumber(numbers[i]);
`validateNumber` 와 `getNumber` 의 역할이 중복으로 판단됩니다.
`Integer.parseInt(number)` 만으로 처리해볼 수 있지 않을까요?

2022-12-30 10:11 UTC, poistargram commented on src/test/java/step1/StringParserTest.java
> +	private void contains(String[] array, String object){
추출한 의도 자체는 contains 테스트 중복의 여지가 있어서 뺐는데 당장은 구문이 간단하여 추출하지 않는 게 낫다고 생각이 듭니다! 추후 로직이 복잡해지고 중복이 된다면 적절한 메스드 명을 줘서 빼보는 걸 다시 고려할게요!

2022-12-30 10:14 UTC, poistargram commented on src/test/java/step1/StringParserTest.java
> +		int index = -1;
local을 선언한 건 테스트 준비 단계에서 의미를 부여하기 위함이 맞구요!
말씀주신 대로 index보다 invalidIndex가 더 좋다는 생각이 듭니다!

2022-12-30 10:16 UTC, poistargram commented on src/test/java/step1/SetTest.java
> +	@CsvSource(value = {"1:true", "2:true", "3:true", "4:false", "5:false"}, delimiter = ':')
좀더 정진하겠습니다.

2022-12-30 10:16 UTC, poistargram commented on src/test/java/step1/SetTest.java
> +		assertThat(numbers.contains(value)).isTrue();
특별한 이유는 없습니다.. ㅎ

2022-12-30 10:22 UTC, poistargram commented on src/main/java/step1/AddCalculator.java
> +		String[] numbers = parseNumbers(string);
String[] 으로 받은 건 나중에 연산자가 섞인 경우를 고려했던 것 같아요(그럼에도 메서드명numbers이긴 하지만,,)
split만으로 custom연산자를 커버할 수 있나요?? 고민해보겠습니다.

2022-12-30 10:23 UTC, poistargram commented on src/main/java/step1/AddCalculator.java
> +			int number = getNumber(numbers[i]);
혹시 try catch로 처리하는 걸까요??
교육 자료에서 try catch는 죄악이라고 봤어서 최대한 지양했습니다 ㅎㅎㅎ

2023-01-01 12:30 UTC, jinuk17 commented on src/test/java/step1/SetTest.java
> +		assertThat(numbers.contains(value)).isTrue();
특별한 이유가 있어야죠 ㅋㅋㅋ

제가 생각하기에는 테스트 검증 대상이 
Set 에 값이 있는걸 검증하는게 아니고, 
Set 의 `contains()` 기능이기 때문에 
의도적으로 호출해서 검증하는게 더 적절해 보였어요 ~

2023-01-01 12:33 UTC, jinuk17 commented on src/main/java/step1/AddCalculator.java
> +			int number = getNumber(numbers[i]);
try/catch 사용이 죄악은 아니고,

`try/catch 블록은 원래가 추하다. 코드 구조에 혼란을 일으키며, 정상적인 동작과 오류 처리 동작을 뒤섞는다. try/catch 블록을 별도 함수로 뽑아내는 편이 낫다` 라고 한 것 같아요 ㅋㅋㅋ

2023-04-05 09:47 UTC, closed without merging